---
- hosts: all
  tasks:
    - name: Show user Ansible is running as
      debug:
        msg: "Ansible user: {{ ansible_user_id }}"

    - name: Show distro information 
      debug:
        msg:
        - "Ansible Distribution: {{ hostvars[inventory_hostname].ansible_distribution }}"
        - "Major Version:        {{ hostvars[inventory_hostname].ansible_distribution_major_version }}"
        - "Version:              {{ hostvars[inventory_hostname].ansible_distribution_version }}"
...