---
# ansible-playbook shutdown-machines.yaml -K -l test
- name: Shutdown machines
  hosts: all
  become: yes
  tasks:

  - name: Unconditionally shut down the machine with all defaults
    community.general.shutdown:
...